name: Validate PR
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  build-bahmni-offlinesync:
    name: Build bahmni-offlinesync
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: mvn clean install -U -PIT